import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import DynamicHeader from "@/components/dynamicheader";
import HeaderSwitcher from "@/components/headerswitcher";
import Footer from "@/footers/footer_minimalcentered";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <DynamicHeader />
        <HeaderSwitcher />
        {children}
        <Footer />
        {/* <footer className="py-8 text-center text-sm text-muted border-t border-base">
          Designed with ❤️ by your Theme Architect.
        </footer> */}
      </body>
    </html>
  );
}
